name: Push Site
on:
  push:
    branches: [main]
jobs:
  Push-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: whoami
        uses: docker://jarhill0/rclone
      - run: rclone --version
        uses: docker://jarhill0/rclone
      - run: ./ci-upload.sh
        uses: docker://jarhill0/rclone
